[package]
name = "tessel-rust-tests"
version = "0.1.0"
authors = ["Tim Ryan <id@timryan.org>"]
publish = false

[dependencies]
nickel = "0.8.1"
rustc-serialize = "0.3"
tessel = "0.3"
accel-mma84 = version = "0.2"
local-ip = "0.1"
